### PR TITLE
Add crystal 0.35.1 support & elasticsearch 7.8

### PR DESCRIPTION
**Pull request by agloks**
Hi, these are the changes was made...

1) fixed shard error, as related in https://github.com/imdrasil/hermes.cr/issues/5

2) replaced time.now to time.local.

3) request without headers was failing, added by default content-type: application/json.

4) method save was crashing, seems that the actual response not coming more "created" as a key on headers.

5) replaced Json::Mapping to JSON::Serializable.

6) Any alias with support to int64.

The feature of creating different type to the same index, seems to be outdated and not is more able in versions more than 6.x, so i changed the UserRepository at test to one own index.
https://www.elastic.co/guide/en/elasticsearch/reference/6.7/removal-of-types.html

### CODE REVIEW

**Comment by imdrasil** [comment]
nice work :+1:  there is setup issue with travis (https://travis-ci.org/github/imdrasil/hermes.cr). Sorry for missing it as a check - ATM I'm experiencing some integration issues with travis-ci

**Comment by agloks** [comment]
oh, that sad, i never have used sam yet, and not had tested with elasticsearch before 6.x, i hope that the conflict not be so big. I don't know what is the root of problem with the the integration, but in case of be the version of elasticsearch, would is worth work in give support to elasticsearch before 6.x? I'll could can see it more later if you want.

**Comment by imdrasil** [comment]
Let's keep support only for 7+ elasticsearch (ATM this has higher priority and valuable). Regarding Sam:
- change it's version to 0.4.0
- change in `.travis.yml` `crystal ./script/runner.cr -- es:index:create_all` -> `crystal ./script/runner.cr es:index:create_all`
- also upgrade elasticsearch version as well

These should be enough :)

**Comment by agloks** [comment]
i've tried 2 builds, both failed, not is being so easy the integration haha, i'll need to take some time to learn how to handle with.

1 build : https://travis-ci.org/github/imdrasil/hermes.cr/builds/717693831
2 build : https://travis-ci.org/github/imdrasil/hermes.cr/builds/717704600

**Comment by imdrasil** [comment]
Good job :+1:. Going to merge and address CI issue by my own

**Pull request merged**
